package unattend

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"html"
	"sort"
	"strings"
)

// PowerSchemeHighPerformance is the well-known Windows GUID for the
// High Performance scheme.
const PowerSchemeHighPerformance = "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"

// Generate writes a complete Windows unattend.xml for s.
//
// Passes:
//
//	windowsPE   — language/keyboard/edition. AutoDeploy applies WIMs
//	              directly so this is largely a courtesy. For Windows 11
//	              we also emit the LabConfig hardware-requirements
//	              bypass here when BypassWin11Reqs is set.
//	specialize  — computer name, time zone, licensing (KMS / AVMA /
//	              skip-auto-activation), Windows-policy registry tweaks
//	              (telemetry, Windows Update, RDP, firewall, power
//	              scheme), optional BypassNRO (Win11), operator-supplied
//	              specialize commands, the SetupComplete.cmd writer,
//	              and the domain-join section if configured.
//	oobeSystem  — OOBE skip flags, every local account, optional
//	              auto-logon, first-logon commands (with the agent
//	              bootstrap always appended).
func Generate(s Settings) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`<?xml version="1.0" encoding="utf-8"?>` + "\n")
	b.WriteString(`<!-- Generated by AutoDeploy for ` + esc(s.TargetOS) + ` -->` + "\n")
	b.WriteString(`<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">` + "\n")

	writeWindowsPE(&b, s)
	writeSpecialize(&b, s)
	writeOOBE(&b, s)

	b.WriteString(`</unattend>` + "\n")
	return b.Bytes(), nil
}

func writeWindowsPE(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <SetupUILanguage><UILanguage>`+esc(s.UILanguage)+`</UILanguage></SetupUILanguage>
      <InputLocale>`+esc(s.Keyboard)+`</InputLocale>
      <SystemLocale>`+esc(s.Locale)+`</SystemLocale>
      <UILanguage>`+esc(s.UILanguage)+`</UILanguage>
      <UserLocale>`+esc(s.Locale)+`</UserLocale>
    </component>
    <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
`)
	// DiskConfiguration + ImageInstall make Setup run UNATTENDED. Without
	// them Setup falls back to the interactive "where to install / load
	// driver" screens. Element order inside the component matters:
	// DiskConfiguration, ImageInstall, RunSynchronous, UserData.
	writeDiskAndImage(b, s)
	if IsWindows11Family(s.TargetOS) && s.BypassWin11Reqs {
		fmt.Fprint(b, `      <RunSynchronous>
        <RunSynchronousCommand wcm:action="add"><Order>1</Order><Description>Bypass Win11: TPM</Description><Path>reg add HKLM\System\Setup\LabConfig /v BypassTPMCheck /t REG_DWORD /d 1 /f</Path></RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add"><Order>2</Order><Description>Bypass Win11: Secure Boot</Description><Path>reg add HKLM\System\Setup\LabConfig /v BypassSecureBootCheck /t REG_DWORD /d 1 /f</Path></RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add"><Order>3</Order><Description>Bypass Win11: RAM</Description><Path>reg add HKLM\System\Setup\LabConfig /v BypassRAMCheck /t REG_DWORD /d 1 /f</Path></RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add"><Order>4</Order><Description>Bypass Win11: CPU</Description><Path>reg add HKLM\System\Setup\LabConfig /v BypassCPUCheck /t REG_DWORD /d 1 /f</Path></RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add"><Order>5</Order><Description>Bypass Win11: Storage</Description><Path>reg add HKLM\System\Setup\LabConfig /v BypassStorageCheck /t REG_DWORD /d 1 /f</Path></RunSynchronousCommand>
      </RunSynchronous>
`)
	}
	fmt.Fprint(b, `      <UserData>
        <AcceptEula>true</AcceptEula>
`)
	if s.ProductKey != "" {
		fmt.Fprintf(b, `        <ProductKey><Key>%s</Key><WillShowUI>OnError</WillShowUI></ProductKey>`+"\n", esc(s.ProductKey))
	}
	fmt.Fprint(b, `      </UserData>
    </component>
  </settings>
`)
}

// writeDiskAndImage emits the DiskConfiguration + ImageInstall that drive
// an unattended install in the boot-the-media model.
//
// Layout (single-disk coexistence): the Boot Client created the FAT32
// AutoDeploy media partition as partition 1 at the END of the disk and
// left the front free. WillWipeDisk=false preserves that media partition;
// Setup creates ESP+MSR+Windows in the free space. Windows numbers
// partitions by on-disk OFFSET, and our media partition sits at the END,
// so the front partitions get the low numbers (EFI=1, MSR=2, Windows=3)
// and the media partition is the highest (4). Windows installs to
// partition 3; the media partition (4) is reclaimed post-install by the
// agent.
//
// ModifyPartitions formats the created partitions: the ESP as FAT32 and
// the OS partition as NTFS. This is NOT optional -- CreatePartition only
// carves the geometry; without a Format the ESP is left raw and Windows
// Setup's boot-file servicing (BFSVC) fails at finalize with 0x800703ED
// (ERROR_UNRECOGNIZED_VOLUME). (ImageInstall happens to format its own
// target, which is why apply succeeds even so, but the ESP needs this.)
//
// NOTE: PartitionID=3 assumes the standard EFI+MSR+Windows triplet ahead
// of the trailing media partition. If a future layout changes the number
// of partitions before the OS partition, this is the knob to adjust.
func writeDiskAndImage(b *bytes.Buffer, s Settings) {
	edition := s.Edition
	if edition == "" {
		edition = "Windows 11 Pro"
	}
	fmt.Fprintf(b, `      <DiskConfiguration>
        <WillShowUI>OnError</WillShowUI>
        <Disk wcm:action="add">
          <DiskID>%d</DiskID>
          <WillWipeDisk>false</WillWipeDisk>
          <CreatePartitions>
            <CreatePartition wcm:action="add"><Order>1</Order><Type>EFI</Type><Size>384</Size></CreatePartition>
            <CreatePartition wcm:action="add"><Order>2</Order><Type>MSR</Type><Size>16</Size></CreatePartition>
            <CreatePartition wcm:action="add"><Order>3</Order><Type>Primary</Type><Extend>true</Extend></CreatePartition>
          </CreatePartitions>
          <ModifyPartitions>
            <ModifyPartition wcm:action="add"><Order>1</Order><PartitionID>1</PartitionID><Format>FAT32</Format><Label>System</Label></ModifyPartition>
            <ModifyPartition wcm:action="add"><Order>2</Order><PartitionID>3</PartitionID><Format>NTFS</Format><Label>Windows</Label></ModifyPartition>
          </ModifyPartitions>
        </Disk>
      </DiskConfiguration>
      <ImageInstall>
        <OSImage>
          <InstallFrom>
            <MetaData wcm:action="add"><Key>/IMAGE/NAME</Key><Value>%s</Value></MetaData>
          </InstallFrom>
          <InstallTo><DiskID>%d</DiskID><PartitionID>3</PartitionID></InstallTo>
          <WillShowUI>OnError</WillShowUI>
        </OSImage>
      </ImageInstall>
`, s.DiskID, esc(edition), s.DiskID)
}

// rsCmd is one RunSynchronousCommand row.
type rsCmd struct {
	order int
	desc  string
	path  string
}

func writeSpecialize(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
`)
	switch s.NameStrategy {
	case "literal":
		fmt.Fprintf(b, `      <ComputerName>%s</ComputerName>`+"\n", esc(s.ComputerName))
	case "prefix":
		fmt.Fprintf(b, `      <ComputerName>%s*</ComputerName>`+"\n", esc(s.ComputerName))
	default:
		fmt.Fprint(b, `      <ComputerName>*</ComputerName>`+"\n")
	}
	fmt.Fprintf(b, `      <TimeZone>%s</TimeZone>`+"\n", esc(s.TimeZone))
	if s.SkipAutoActivation {
		fmt.Fprint(b, `      <SkipAutoActivation>true</SkipAutoActivation>`+"\n")
	}
	fmt.Fprint(b, `    </component>
`)

	cmds := buildSpecializeCommands(s)
	if len(cmds) > 0 {
		fmt.Fprint(b, `    <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <RunSynchronous>
`)
		for _, c := range cmds {
			fmt.Fprintf(b, `        <RunSynchronousCommand wcm:action="add"><Order>%d</Order><Description>%s</Description><Path>%s</Path></RunSynchronousCommand>`+"\n",
				c.order, esc(c.desc), esc(c.path))
		}
		fmt.Fprint(b, `      </RunSynchronous>
    </component>
`)
	}

	if s.DomainJoin != nil {
		writeDomainJoin(b, s.DomainJoin)
	}
	fmt.Fprint(b, `  </settings>
`)
}

// buildSpecializeCommands assembles the operator-controlled commands
// that should run during the specialize pass, in order.
func buildSpecializeCommands(s Settings) []rsCmd {
	var cmds []rsCmd
	order := 1
	push := func(desc, path string) {
		cmds = append(cmds, rsCmd{order: order, desc: desc, path: path})
		order++
	}

	if IsWindows11Family(s.TargetOS) && s.BypassNRO {
		push("Windows 11: bypass OOBE network requirement",
			`reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f`)
	}

	// Licensing.
	if s.KMSServer != "" {
		port := s.KMSPort
		if port == 0 {
			port = 1688
		}
		push("Licensing: set KMS server",
			fmt.Sprintf(`cscript //nologo %%SystemRoot%%\System32\slmgr.vbs /skms %s:%d`, s.KMSServer, port))
	}
	if s.AVMAKey != "" {
		push("Licensing: install AVMA key",
			fmt.Sprintf(`cscript //nologo %%SystemRoot%%\System32\slmgr.vbs /ipk %s`, s.AVMAKey))
	}

	// Telemetry policy (1-3). 0 / negative leave the system default.
	if s.TelemetryLevel >= 1 && s.TelemetryLevel <= 3 {
		push(fmt.Sprintf("Policy: AllowTelemetry = %d", s.TelemetryLevel),
			fmt.Sprintf(`reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\DataCollection /v AllowTelemetry /t REG_DWORD /d %d /f`,
				s.TelemetryLevel))
	}

	// Windows Update policy.
	if s.DisableWindowsUpdate {
		push("Policy: disable Windows Update auto-install",
			`reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU /v NoAutoUpdate /t REG_DWORD /d 1 /f`)
	}
	if s.DeferFeatureUpdatesDays > 0 {
		push(fmt.Sprintf("Policy: defer feature updates %d days", s.DeferFeatureUpdatesDays),
			fmt.Sprintf(`reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate /v DeferFeatureUpdatesPeriodInDays /t REG_DWORD /d %d /f`,
				s.DeferFeatureUpdatesDays))
	}
	if s.DeferQualityUpdatesDays > 0 {
		push(fmt.Sprintf("Policy: defer quality updates %d days", s.DeferQualityUpdatesDays),
			fmt.Sprintf(`reg add HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate /v DeferQualityUpdatesPeriodInDays /t REG_DWORD /d %d /f`,
				s.DeferQualityUpdatesDays))
	}

	// RDP + firewall.
	if s.EnableRDP {
		push("Networking: enable RDP",
			`reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f`)
		push("Networking: open firewall for RDP",
			`netsh advfirewall firewall set rule group="remote desktop" new enable=Yes`)
	}
	if s.AllowICMPv4 {
		push("Networking: allow ICMPv4 echo",
			`netsh advfirewall firewall add rule name="AutoDeploy: ICMPv4-In" protocol=icmpv4:8,any dir=in action=allow`)
	}

	// Power scheme.
	if strings.EqualFold(s.PowerScheme, "high") {
		push("Power: set High Performance scheme",
			"powercfg /setactive "+PowerSchemeHighPerformance)
	}

	// Operator-supplied specialize commands (after the system ones so
	// operators can rely on the policy state when their command runs).
	specOps := append([]SpecializeCommand(nil), s.SpecializeCommands...)
	sort.SliceStable(specOps, func(i, j int) bool { return specOps[i].Order < specOps[j].Order })
	for _, c := range specOps {
		if strings.TrimSpace(c.CommandLine) == "" {
			continue
		}
		desc := c.Description
		if desc == "" {
			desc = "Operator specialize command"
		}
		push(desc, c.CommandLine)
	}

	// SetupComplete.cmd: write the script file so Windows runs it
	// before OOBE finishes. We use PowerShell to base64-decode the
	// script into the file; PowerShell ships on every supported
	// Windows release, handles any byte safely, and avoids the
	// quoting headaches of building the script via cmd echo lines.
	if writer := buildSetupCompleteWriter(s.SetupCompleteCommands); writer != "" {
		push("SetupComplete: write Scripts\\SetupComplete.cmd", writer)
	}

	return cmds
}

// buildSetupCompleteWriter returns a single PowerShell-based command
// that writes %WINDIR%\Setup\Scripts\SetupComplete.cmd from a
// base64-encoded payload. Empty input returns "".
func buildSetupCompleteWriter(cmds []SetupCompleteCommand) string {
	if len(cmds) == 0 {
		return ""
	}
	sorted := append([]SetupCompleteCommand(nil), cmds...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].Order < sorted[j].Order })
	var buf bytes.Buffer
	buf.WriteString("@echo off\r\n")
	buf.WriteString("rem Generated by AutoDeploy\r\n")
	for _, c := range sorted {
		line := strings.TrimSpace(c.CommandLine)
		if line == "" {
			continue
		}
		if c.Description != "" {
			fmt.Fprintf(&buf, "rem %s\r\n", strings.ReplaceAll(c.Description, "\n", " "))
		}
		buf.WriteString(line)
		buf.WriteString("\r\n")
	}
	enc := base64.StdEncoding.EncodeToString(buf.Bytes())
	// Single-line PowerShell that ensures the Scripts directory exists
	// then writes the decoded bytes.
	ps := `$d='` + enc + `'; ` +
		`$dir=Join-Path $env:WINDIR 'Setup\Scripts'; ` +
		`if(!(Test-Path $dir)){New-Item -ItemType Directory -Path $dir -Force | Out-Null}; ` +
		`[IO.File]::WriteAllBytes((Join-Path $dir 'SetupComplete.cmd'),[Convert]::FromBase64String($d))`
	return "powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command \"" + ps + "\""
}

func writeDomainJoin(b *bytes.Buffer, d *DomainJoin) {
	fmt.Fprint(b, `    <component name="Microsoft-Windows-UnattendedJoin" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <Identification>
        <Credentials>
          <Domain>`+esc(d.Domain)+`</Domain>
          <Username>`+esc(d.JoinUser)+`</Username>
          <Password>`+esc(d.JoinPassword)+`</Password>
        </Credentials>
        <JoinDomain>`+esc(d.Domain)+`</JoinDomain>
`)
	if d.OU != "" {
		fmt.Fprintf(b, `        <MachineObjectOU>%s</MachineObjectOU>`+"\n", esc(d.OU))
	}
	fmt.Fprint(b, `      </Identification>
    </component>
`)
}

func writeOOBE(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>`+boolStr(s.HideEULA)+`</HideEULAPage>
        <HideOEMRegistrationScreen>`+boolStr(s.HideOEMRegistration)+`</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>`+boolStr(s.HideOnlineAccountScreens)+`</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>`+boolStr(s.HideWirelessSetup)+`</HideWirelessSetupInOOBE>
        <ProtectYourPC>`+fmt.Sprint(s.ProtectYourPC)+`</ProtectYourPC>
`)
	if s.SkipMachineOOBE {
		fmt.Fprint(b, `        <SkipMachineOOBE>true</SkipMachineOOBE>`+"\n")
	}
	if s.SkipUserOOBE {
		fmt.Fprint(b, `        <SkipUserOOBE>true</SkipUserOOBE>`+"\n")
	}
	fmt.Fprint(b, `      </OOBE>
`)

	// Local accounts. The first Administrators-group account
	// additionally fills <AdministratorPassword> (the legacy built-in
	// Administrator) so installs that disable LocalAccounts entirely
	// still have a usable elevated credential.
	writeUserAccounts(b, s)

	// AutoLogon.
	if s.AutoLogon != nil && s.AutoLogon.Username != "" && s.AutoLogon.Count > 0 {
		fmt.Fprintf(b, `      <AutoLogon>
        <Enabled>true</Enabled>
        <Username>%s</Username>
        <Password><Value>%s</Value><PlainText>true</PlainText></Password>
        <LogonCount>%d</LogonCount>
      </AutoLogon>
`, esc(s.AutoLogon.Username), esc(s.AutoLogon.Password), s.AutoLogon.Count)
	}

	// First-logon commands: operator-defined only, sorted by Order. The
	// AutoDeploy agent is NOT bootstrapped here anymore -- it's injected
	// into the installed OS via the boot media's $OEM$ tree and installed
	// by SetupComplete.cmd, which runs as SYSTEM at the end of Setup with
	// no network/first-logon dependency. Omit the block entirely when the
	// operator defined no commands (an empty <FirstLogonCommands> is
	// pointless and some Setup builds dislike it).
	cmds := append([]FirstLogonCommand(nil), s.FirstLogonCommands...)
	sort.SliceStable(cmds, func(i, j int) bool { return cmds[i].Order < cmds[j].Order })
	if len(cmds) > 0 {
		fmt.Fprint(b, `      <FirstLogonCommands>
`)
		for i, c := range cmds {
			fmt.Fprintf(b, `        <SynchronousCommand wcm:action="add">
          <Order>%d</Order>
          <Description>%s</Description>
          <CommandLine>%s</CommandLine>
        </SynchronousCommand>
`, i+1, esc(c.Description), esc(c.CommandLine))
		}
		fmt.Fprint(b, `      </FirstLogonCommands>
`)
	}
	fmt.Fprint(b, `    </component>
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>`+esc(s.Keyboard)+`</InputLocale>
      <SystemLocale>`+esc(s.Locale)+`</SystemLocale>
      <UILanguage>`+esc(s.UILanguage)+`</UILanguage>
      <UserLocale>`+esc(s.Locale)+`</UserLocale>
    </component>
  </settings>
`)
}

// writeUserAccounts emits the <UserAccounts> block from the unified
// LocalAccounts list. Falls through to the legacy single-admin
// behaviour when LocalAccounts is empty.
func writeUserAccounts(b *bytes.Buffer, s Settings) {
	accounts := s.LocalAccounts
	// Compatibility: if the operator used the old admin-user fields
	// and Parse hasn't already migrated them, do it now.
	if len(accounts) == 0 && !s.HideAdmin && s.AdminUser != "" {
		accounts = []LocalAccount{{
			Name: s.AdminUser, Password: s.AdminPassword, Group: "Administrators",
		}}
	}
	if len(accounts) == 0 && s.HideAdmin {
		return
	}
	if len(accounts) == 0 {
		return
	}

	fmt.Fprint(b, `      <UserAccounts>
`)
	// The first Administrators-group account also goes into
	// <AdministratorPassword> so workflows that look at the built-in
	// Administrator credential still find a usable password. The
	// account itself is also listed in <LocalAccounts> so it's
	// visible alongside the others.
	for _, a := range accounts {
		if strings.EqualFold(a.Group, "Administrators") && a.Password != "" {
			fmt.Fprintf(b, `        <AdministratorPassword>
          <Value>%s</Value>
          <PlainText>true</PlainText>
        </AdministratorPassword>
`, esc(a.Password))
			break
		}
	}
	fmt.Fprint(b, `        <LocalAccounts>
`)
	for _, a := range accounts {
		group := a.Group
		if group == "" {
			group = "Users"
		}
		fmt.Fprintf(b, `          <LocalAccount wcm:action="add">
            <Name>%s</Name>
            <Group>%s</Group>
`, esc(a.Name), esc(group))
		if a.FullName != "" {
			fmt.Fprintf(b, `            <DisplayName>%s</DisplayName>`+"\n", esc(a.FullName))
		}
		if a.Description != "" {
			fmt.Fprintf(b, `            <Description>%s</Description>`+"\n", esc(a.Description))
		}
		fmt.Fprintf(b, `            <Password>
              <Value>%s</Value>
              <PlainText>true</PlainText>
            </Password>
          </LocalAccount>
`, esc(a.Password))
	}
	fmt.Fprint(b, `        </LocalAccounts>
      </UserAccounts>
`)
}

func esc(s string) string { return html.EscapeString(s) }

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

// XMLContainsSecret reports whether x mentions one of the supplied secret
// values literally. Tests use this to assert that generated XML really did
// carry the password (necessary for the OS to install) while logs do not.
func XMLContainsSecret(x []byte, secret string) bool {
	if secret == "" {
		return false
	}
	return bytes.Contains(x, []byte(secret)) ||
		strings.Contains(string(x), esc(secret))
}
