package unattend

import (
	"encoding/xml"
	"strings"
	"testing"
)

func TestGenerateDefaultsIsValidXML(t *testing.T) {
	x, err := Generate(Defaults())
	if err != nil {
		t.Fatal(err)
	}
	var any struct {
		XMLName xml.Name
	}
	if err := xml.Unmarshal(x, &any); err != nil {
		t.Fatalf("generated XML failed to parse: %v\n---\n%s", err, x)
	}
	if any.XMLName.Local != "unattend" {
		t.Errorf("root = %q, want unattend", any.XMLName.Local)
	}
}

func TestGenerateIncludesAdminPassword(t *testing.T) {
	s := Defaults()
	s.AdminPassword = "Hunter2-NotReal"
	x, _ := Generate(s)
	if !XMLContainsSecret(x, s.AdminPassword) {
		t.Errorf("admin password missing from XML; unattended setup would fail")
	}
}

func TestGenerateOmitsAdminWhenHidden(t *testing.T) {
	s := Defaults()
	s.HideAdmin = true
	s.AdminPassword = "should-not-appear"
	x, _ := Generate(s)
	if strings.Contains(string(x), "should-not-appear") {
		t.Error("hidden admin: password leaked into XML")
	}
	if strings.Contains(string(x), "<AdministratorPassword>") {
		t.Error("hidden admin: AdministratorPassword block should be absent")
	}
}

func TestGenerateAlwaysIncludesAgentBootstrap(t *testing.T) {
	x, _ := Generate(Defaults())
	if !strings.Contains(string(x), "autodeploy-agent") {
		t.Errorf("expected agent bootstrap in FirstLogonCommands; got\n%s", x)
	}
}

func TestGenerateWin11AddsBypassNRO(t *testing.T) {
	s := Defaults()
	s.TargetOS = "windows-11"
	s.BypassNRO = true
	x, _ := Generate(s)
	if !strings.Contains(string(x), "BypassNRO") {
		t.Errorf("Windows 11 unattend should set BypassNRO; got\n%s", x)
	}
	if !strings.Contains(string(x), "Microsoft-Windows-Deployment") {
		t.Errorf("Windows 11 BypassNRO should be in Deployment component; got\n%s", x)
	}
}

func TestGenerateWin10OmitsBypassNRO(t *testing.T) {
	s := Defaults()
	s.TargetOS = "windows-10"
	s.BypassNRO = true // honored only on Win11
	x, _ := Generate(s)
	if strings.Contains(string(x), "BypassNRO") {
		t.Errorf("Windows 10 unattend should NOT emit BypassNRO; got\n%s", x)
	}
}

func TestGenerateBypassWin11ReqsOnlyWhenOpted(t *testing.T) {
	s := Defaults()
	s.TargetOS = "windows-11"
	s.BypassWin11Reqs = false
	x, _ := Generate(s)
	if strings.Contains(string(x), "BypassTPMCheck") {
		t.Error("BypassWin11Reqs default should NOT include LabConfig keys")
	}
	s.BypassWin11Reqs = true
	x, _ = Generate(s)
	for _, want := range []string{"BypassTPMCheck", "BypassSecureBootCheck", "BypassRAMCheck", "BypassCPUCheck", "BypassStorageCheck"} {
		if !strings.Contains(string(x), want) {
			t.Errorf("BypassWin11Reqs=true should emit %s", want)
		}
	}
}

func TestGenerateBypassWin11ReqsIgnoredForWin10(t *testing.T) {
	s := Defaults()
	s.TargetOS = "windows-10"
	s.BypassWin11Reqs = true
	x, _ := Generate(s)
	if strings.Contains(string(x), "BypassTPMCheck") {
		t.Error("Win10 should not get the LabConfig bypass even when the flag is on")
	}
}

func TestTargetOSCommentInHeader(t *testing.T) {
	for _, os := range []string{"windows-11", "windows-10", "windows-server-2022"} {
		s := Defaults()
		s.TargetOS = os
		x, _ := Generate(s)
		if !strings.Contains(string(x), "Generated by AutoDeploy for "+os) {
			t.Errorf("expected target OS comment for %s", os)
		}
	}
}

func TestNameStrategies(t *testing.T) {
	cases := []struct {
		strat, name, want string
	}{
		{"random", "ignored", "<ComputerName>*</ComputerName>"},
		{"literal", "LAB-01", "<ComputerName>LAB-01</ComputerName>"},
		{"prefix", "LAB", "<ComputerName>LAB*</ComputerName>"},
	}
	for _, tc := range cases {
		s := Defaults()
		s.NameStrategy = tc.strat
		s.ComputerName = tc.name
		x, _ := Generate(s)
		if !strings.Contains(string(x), tc.want) {
			t.Errorf("strategy %s: missing %q in XML\n%s", tc.strat, tc.want, x)
		}
	}
}

func TestDomainJoinIncluded(t *testing.T) {
	s := Defaults()
	s.DomainJoin = &DomainJoin{
		Domain:       "corp.example",
		OU:           "OU=Lab,DC=corp,DC=example",
		JoinUser:     "joiner@corp.example",
		JoinPassword: "join-password-not-real",
	}
	x, _ := Generate(s)
	for _, w := range []string{
		"<JoinDomain>corp.example</JoinDomain>",
		"<MachineObjectOU>OU=Lab,DC=corp,DC=example</MachineObjectOU>",
		"joiner@corp.example",
		"join-password-not-real",
	} {
		if !strings.Contains(string(x), w) {
			t.Errorf("domain join: missing %q", w)
		}
	}
}

func TestParseAppliesDefaults(t *testing.T) {
	s, err := Parse(`{"computer_name":"LAB-01","name_strategy":"literal"}`)
	if err != nil {
		t.Fatal(err)
	}
	if s.Locale != "en-US" {
		t.Errorf("default locale not applied: %+v", s)
	}
	if s.ComputerName != "LAB-01" {
		t.Errorf("ComputerName lost: %+v", s)
	}
}
