package unattend

import (
	"bytes"
	"fmt"
	"html"
	"strings"
)

// AgentInstallCommand is the synchronous first-logon command that bootstraps
// the AutoDeploy agent on the freshly imaged machine. It is appended to the
// operator's first-logon list automatically by Generate.
const AgentInstallCommand = `cmd /c start /b "" \\Windows\\AutoDeploy\\autodeploy-agent.exe --server %AUTODEPLOY_SERVER%`

// Generate writes a complete Windows unattend.xml for s.
//
// The generated XML covers three passes:
//
//   windowsPE       — language/keyboard/disk/edition. AutoDeploy applies
//                     WIMs directly so this pass is largely a courtesy
//                     for operators who reuse the same unattend with
//                     Windows Setup. For Windows 11 we also emit
//                     RunSynchronousCommand entries here that set the
//                     LabConfig registry keys when BypassWin11Reqs is on,
//                     so an unattended install survives a hardware
//                     requirements check.
//   specialize      — computer name, time zone, optional BypassNRO write
//                     (Win11 22H2+), domain join, agent bootstrap path.
//   oobeSystem      — OOBE skip flags, local admin, first-logon commands.
//
// Branches on s.TargetOS so the right schema goes to the right OS.
func Generate(s Settings) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString(`<?xml version="1.0" encoding="utf-8"?>` + "\n")
	b.WriteString(`<!-- Generated by AutoDeploy for ` + esc(s.TargetOS) + ` -->` + "\n")
	b.WriteString(`<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">` + "\n")

	writeWindowsPE(&b, s)
	writeSpecialize(&b, s)
	writeOOBE(&b, s)

	b.WriteString(`</unattend>` + "\n")
	return b.Bytes(), nil
}

func writeWindowsPE(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="windowsPE">
    <component name="Microsoft-Windows-International-Core-WinPE" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <SetupUILanguage><UILanguage>`+esc(s.UILanguage)+`</UILanguage></SetupUILanguage>
      <InputLocale>`+esc(s.Keyboard)+`</InputLocale>
      <SystemLocale>`+esc(s.Locale)+`</SystemLocale>
      <UILanguage>`+esc(s.UILanguage)+`</UILanguage>
      <UserLocale>`+esc(s.Locale)+`</UserLocale>
    </component>
    <component name="Microsoft-Windows-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <UserData>
        <AcceptEula>true</AcceptEula>
`)
	if s.ProductKey != "" {
		fmt.Fprintf(b, `        <ProductKey><Key>%s</Key><WillShowUI>OnError</WillShowUI></ProductKey>`+"\n", esc(s.ProductKey))
	}
	fmt.Fprint(b, `      </UserData>
`)
	// Windows 11 hardware-requirements bypass — only when the operator
	// explicitly opted in. Writes the LabConfig registry keys Setup
	// checks during the requirements pass.
	if IsWindows11Family(s.TargetOS) && s.BypassWin11Reqs {
		fmt.Fprint(b, `      <RunSynchronous>
        <RunSynchronousCommand wcm:action="add">
          <Order>1</Order><Description>Bypass Win11: TPM</Description>
          <Path>reg add HKLM\System\Setup\LabConfig /v BypassTPMCheck /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>2</Order><Description>Bypass Win11: Secure Boot</Description>
          <Path>reg add HKLM\System\Setup\LabConfig /v BypassSecureBootCheck /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>3</Order><Description>Bypass Win11: RAM</Description>
          <Path>reg add HKLM\System\Setup\LabConfig /v BypassRAMCheck /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>4</Order><Description>Bypass Win11: CPU</Description>
          <Path>reg add HKLM\System\Setup\LabConfig /v BypassCPUCheck /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>5</Order><Description>Bypass Win11: Storage</Description>
          <Path>reg add HKLM\System\Setup\LabConfig /v BypassStorageCheck /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
      </RunSynchronous>
`)
	}
	fmt.Fprint(b, `    </component>
  </settings>
`)
}

func writeSpecialize(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
`)
	switch s.NameStrategy {
	case "literal":
		fmt.Fprintf(b, `      <ComputerName>%s</ComputerName>`+"\n", esc(s.ComputerName))
	case "prefix":
		// "*" means Windows will use the machine's UUID-based default; we
		// can't compute the serial here, so the agent renames the machine
		// authoritatively post-deploy (Phase 13 bulk rename). Use a
		// prefix-* hint so the initial Windows name is identifiable.
		fmt.Fprintf(b, `      <ComputerName>%s*</ComputerName>`+"\n", esc(s.ComputerName))
	default: // "random"
		fmt.Fprint(b, `      <ComputerName>*</ComputerName>`+"\n")
	}
	fmt.Fprintf(b, `      <TimeZone>%s</TimeZone>`+"\n", esc(s.TimeZone))
	fmt.Fprint(b, `    </component>
`)
	// Windows 11 22H2+ OOBE forces an online Microsoft Account on Home
	// and Pro unless BypassNRO is set in the registry before the OOBE
	// network pages run. Setting it from specialize via
	// RunSynchronousCommand is the documented unattend approach.
	if IsWindows11Family(s.TargetOS) && s.BypassNRO {
		fmt.Fprint(b, `    <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <RunSynchronous>
        <RunSynchronousCommand wcm:action="add">
          <Order>1</Order><Description>Windows 11: Bypass OOBE network requirement</Description>
          <Path>reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OOBE /v BypassNRO /t REG_DWORD /d 1 /f</Path>
        </RunSynchronousCommand>
      </RunSynchronous>
    </component>
`)
	}
	if s.DomainJoin != nil {
		writeDomainJoin(b, s.DomainJoin)
	}
	fmt.Fprint(b, `  </settings>
`)
}

func writeDomainJoin(b *bytes.Buffer, d *DomainJoin) {
	fmt.Fprint(b, `    <component name="Microsoft-Windows-UnattendedJoin" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <Identification>
        <Credentials>
          <Domain>`+esc(d.Domain)+`</Domain>
          <Username>`+esc(d.JoinUser)+`</Username>
          <Password>`+esc(d.JoinPassword)+`</Password>
        </Credentials>
        <JoinDomain>`+esc(d.Domain)+`</JoinDomain>
`)
	if d.OU != "" {
		fmt.Fprintf(b, `        <MachineObjectOU>%s</MachineObjectOU>`+"\n", esc(d.OU))
	}
	fmt.Fprint(b, `      </Identification>
    </component>
`)
}

func writeOOBE(b *bytes.Buffer, s Settings) {
	fmt.Fprint(b, `  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>`+boolStr(s.HideEULA)+`</HideEULAPage>
        <HideOEMRegistrationScreen>`+boolStr(s.HideOEMRegistration)+`</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>`+boolStr(s.HideOnlineAccountScreens)+`</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>`+boolStr(s.HideWirelessSetup)+`</HideWirelessSetupInOOBE>
        <ProtectYourPC>`+fmt.Sprint(s.ProtectYourPC)+`</ProtectYourPC>
`)
	if s.SkipMachineOOBE {
		fmt.Fprint(b, `        <SkipMachineOOBE>true</SkipMachineOOBE>`+"\n")
	}
	if s.SkipUserOOBE {
		fmt.Fprint(b, `        <SkipUserOOBE>true</SkipUserOOBE>`+"\n")
	}
	fmt.Fprint(b, `      </OOBE>
`)
	if !s.HideAdmin && s.AdminUser != "" {
		fmt.Fprintf(b, `      <UserAccounts>
        <AdministratorPassword>
          <Value>%s</Value>
          <PlainText>true</PlainText>
        </AdministratorPassword>
      </UserAccounts>
`, esc(s.AdminPassword))
	}
	// First-logon: sort operator commands by Order, then append the
	// AutoDeploy agent bootstrap so it always runs after operator setup.
	cmds := append([]FirstLogonCommand(nil), s.FirstLogonCommands...)
	sortByOrder(cmds)
	cmds = append(cmds, FirstLogonCommand{
		Order:       lastOrder(cmds) + 10,
		Description: "Start AutoDeploy agent",
		CommandLine: AgentInstallCommand,
	})
	fmt.Fprint(b, `      <FirstLogonCommands>
`)
	for i, c := range cmds {
		fmt.Fprintf(b, `        <SynchronousCommand wcm:action="add">
          <Order>%d</Order>
          <Description>%s</Description>
          <CommandLine>%s</CommandLine>
        </SynchronousCommand>
`, i+1, esc(c.Description), esc(c.CommandLine))
	}
	fmt.Fprint(b, `      </FirstLogonCommands>
    </component>
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>`+esc(s.Keyboard)+`</InputLocale>
      <SystemLocale>`+esc(s.Locale)+`</SystemLocale>
      <UILanguage>`+esc(s.UILanguage)+`</UILanguage>
      <UserLocale>`+esc(s.Locale)+`</UserLocale>
    </component>
  </settings>
`)
}

func esc(s string) string { return html.EscapeString(s) }

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func sortByOrder(cmds []FirstLogonCommand) {
	// Insertion sort; expected N is small (handful).
	for i := 1; i < len(cmds); i++ {
		for j := i; j > 0 && cmds[j-1].Order > cmds[j].Order; j-- {
			cmds[j-1], cmds[j] = cmds[j], cmds[j-1]
		}
	}
}

func lastOrder(cmds []FirstLogonCommand) int {
	if len(cmds) == 0 {
		return 0
	}
	return cmds[len(cmds)-1].Order
}

// XMLContainsSecret reports whether x mentions one of the supplied secret
// values literally. Tests use this to assert that generated XML really did
// carry the password (necessary for the OS to install) while logs do not.
func XMLContainsSecret(x []byte, secret string) bool {
	if secret == "" {
		return false
	}
	return bytes.Contains(x, []byte(secret)) ||
		strings.Contains(string(x), esc(secret))
}
